### ISSUE TITLE
I have been oppressed

### ISSUE THREAD

**Issue by apertix** [slcoolj/Dickslap#1]
As a queer-kin pansexual demigod I'm highly offended by all the ridiculous and offensive language. I request that this repository be revised or removed immediately. I also request to be financially compensated for my emotional distress.

**Comment by slcoolj** [comment]
I am afraid that I must deny your request for financial compensation and I apologize for you being offended by the "ridiculous" language present within the repository.

I'd recommend creating your own fork of Dickslap if you would like to remove the "ridiculous" language you have found within it.

Have a nice day friend!
